DELETE FROM swarm_scores;
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Watarrka4', 'Three Nations', '3N70', 16.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Wollemi4', 'Three Nations', '3N71', 28);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Yarrobil4', 'Three Nations', '3N72', 15);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Ningaloo3', 'Three Nations', '3N73', 8.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Nymboida3', 'Three Nations', '3N74', 19.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tanami3', 'Three Nations', '3N75', 19.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tidbinbilla3', 'Three Nations', '3N76', 17.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Tooloom3', 'Three Nations', '3N77', 26.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Torndirrup3', 'Three Nations', '3N78', 25.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Gundabooka2', 'Three Nations', '3N79', 21.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Indwarra2', 'Three Nations', '3N80', 24);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Karijini2', 'Three Nations', '3N81', 25.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Meroo2', 'Three Nations', '3N83', 26.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Moorrinya2', 'Three Nations', '3N84', 30);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Bogong1', 'Three Nations', '3N85', 11.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Brindabella1', 'Three Nations', '3N86', 14);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Coorong1', 'Three Nations', '3N88', 30.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Danbulla1', 'Three Nations', '3N89', 15.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Garrawilla1', 'Three Nations', '3N90', 18.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Meroo2', 'How Did Arthur Allen Die?', 'AA10', 21);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Moorrinya2', 'How Did Arthur Allen Die?', 'AA10', 26.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Bogong1', 'How Did Arthur Allen Die?', 'AA10', 20.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Brindabella1', 'How Did Arthur Allen Die?', 'AA10', 20);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Cocoparra1', 'How Did Arthur Allen Die?', 'AA10', 18.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Coorong1', 'How Did Arthur Allen Die?', 'AA11', 25.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Danbulla1', 'How Did Arthur Allen Die?', 'AA11', 20.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Garrawilla1', 'How Did Arthur Allen Die?', 'AA11', 19.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Ulidarra4', 'How Did Arthur Allen Die?', 'AA11', 18.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Warrabah4', 'How Did Arthur Allen Die?', 'AA11', 25.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Witjira4', 'How Did Arthur Allen Die?', 'AA11', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Watarrka4', 'How Did Arthur Allen Die?', 'AA11', 19.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Wollemi4', 'How Did Arthur Allen Die?', 'AA11', 23.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Yarrobil4', 'How Did Arthur Allen Die?', 'AA11', 18);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Nymboida3', 'How Did Arthur Allen Die?', 'AA12', 28.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tanami3', 'How Did Arthur Allen Die?', 'AA12', 24.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tidbinbilla3', 'How Did Arthur Allen Die?', 'AA12', 24.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Tooloom3', 'How Did Arthur Allen Die?', 'AA12', 28);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Torndirrup3', 'How Did Arthur Allen Die?', 'AA12', 25);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Danbulla1', 'Drug Interdiction', 'DS44', 25.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Garrawilla1', 'Drug Interdiction', 'DS45', 18.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Ulidarra4', 'Drug Interdiction', 'DS46', 22.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Warrabah4', 'Drug Interdiction', 'DS47', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Witjira4', 'Drug Interdiction', 'DS48', 21.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Watarrka4', 'Drug Interdiction', 'DS49', 25.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Wollemi4', 'Drug Interdiction', 'DS50', 24.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Yarrobil4', 'Drug Interdiction', 'DS51', 17.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Nymboida3', 'Drug Interdiction', 'DS53', 27);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tanami3', 'Drug Interdiction', 'DS54', 22.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Tidbinbilla3', 'Drug Interdiction', 'DS55', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Tooloom3', 'Drug Interdiction', 'DS56', 30);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Torndirrup3', 'Drug Interdiction', 'DS57', 25.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Gundabooka2', 'Drug Interdiction', 'DS58', 19);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Indwarra2', 'Drug Interdiction', 'DS59', 30.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Karijini2', 'Drug Interdiction', 'DS60', 26.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Meroo2', 'Drug Interdiction', 'DS62', 29.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Moorrinya2', 'Drug Interdiction', 'DS63', 28.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Tooloom3', 'Kalukistan', 'KAL1', 21);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Torndirrup3', 'Kalukistan', 'KAL1', 25);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Gundabooka2', 'Kalukistan', 'KAL1', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Indwarra2', 'Kalukistan', 'KAL1', 22.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Karijini2', 'Kalukistan', 'KAL1', 24);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Koreelah2', 'Kalukistan', 'KAL1', 20.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Meroo2', 'Kalukistan', 'KAL1', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Moorrinya2', 'Kalukistan', 'KAL1', 25);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Bogong1', 'Kalukistan', 'KAL1', 15.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Brindabella1', 'Kalukistan', 'KAL1', 18);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Cocoparra1', 'Kalukistan', 'KAL1', 22.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Coorong1', 'Kalukistan', 'KAL1', 25.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Danbulla1', 'Kalukistan', 'KAL1', 17.67);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Garrawilla1', 'Kalukistan', 'KAL1', 18);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Ulidarra4', 'Kalukistan', 'KAL1', 15.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('AA', 'Warrabah4', 'Kalukistan', 'KAL1', 18);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('PA', 'Witjira4', 'Kalukistan', 'KAL1', 17.33);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Watarrka4', 'Kalukistan', 'KAL1', 17);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Wollemi4', 'Kalukistan', 'KAL1', 14);
INSERT INTO public.swarm_scores (team_type, team, problem, code, score) VALUES ('GP', 'Yarrobil4', 'Kalukistan', 'KAL1', 25);